// src/utils/getCommonSpecifications.js

export function getCommonSpecifications(category) {
    const specsMap = {
        Photography: [
            'Unlimited Shots',
            'Edited Photos Included',
            'Online Gallery Access',
            'USB Copy of Photos',
            'On-site Printing',
            'Drone Photography',
            'Pre-Event Shoot',
            'Studio Session',
            'Event Coverage',
            'Same-Day Edit',
            'Lighting Setup',
            'High-Resolution Output',
            'Candid Shots',
            'Photo Booth Option',
            'Team of Photographers',
        ],

        Videography: [
            'Full Event Coverage',
            'Highlight Reel',
            'Drone Footage',
            '4K Video Quality',
            'Multi-Camera Setup',
            'Edited Video Included',
            'Teaser Trailer',
            'Same-Day Edit',
            'Cinematic Color Grading',
            'Wireless Audio Capture',
            'Storyboarding Session',
            'Interviews Included',
            'Raw Footage Copy',
            'Event Teaser',
            'Social Media Edit',
        ],

        Catering: [
            'Buffet Setup',
            'Plated Service',
            'Cocktail Service',
            'Tableware Included',
            'Menu Customization',
            'Dessert Station',
            'Wait Staff Included',
            'On-site Chef',
            'Beverage Service',
            'Food Tasting Session',
            'Vegetarian Options',
            'Seafood Menu',
            'Halal Certified',
            'Delivery and Setup',
            'Clean-up After Event',
        ],

        'Makeup Artist': [
            'Bridal Makeup',
            'Groom Makeup',
            'Entourage Makeup',
            'Airbrush Technique',
            'Traditional Makeup',
            'Touch-up Kit Included',
            'Trial Makeup Session',
            'On-location Service',
            'Hair Styling Included',
            'False Lashes Included',
            'HD Makeup Finish',
            'Long-Lasting Formula',
            'Natural Look Option',
            'Glam Look Option',
            'Male Grooming Available',
        ],

        'Sound System': [
            'Main Speakers',
            'Subwoofers',
            'Stage Monitors',
            'Wireless Microphones',
            'Mixer Console',
            'Sound Technician',
            'Backup Equipment',
            'Power Amplifiers',
            'DJ Setup',
            'Equalization Support',
            'PA System',
            'Stage Audio Setup',
            'Line Array Setup',
            'Lighting Integration',
            'Sound Check Included',
        ],

        'Lights and Effects': [
            'LED Uplighting',
            'Moving Head Lights',
            'Laser Effects',
            'Fog Machine',
            'Haze Machine',
            'Strobe Lights',
            'Black Lights',
            'Pin Spotting',
            'Gobo Projection',
            'Color Wash',
            'DMX Controlled',
            'Wireless Control',
            'Outdoor Rated',
            'Dance Floor Lighting',
            'Stage Lighting',
            'Mood Lighting',
            'Intelligent Lighting',
            'Follow Spot',
        ],

        'Host / Emcee': [
            'Bilingual Hosting',
            'Event Flow Coordination',
            'Audience Engagement',
            'Customized Script',
            'Formal and Casual Style',
            'Games and Interaction',
            'Corporate Event Hosting',
            'Wedding Hosting',
            'Birthday Hosting',
            'Voice Modulation Skills',
            'Event Planning Assistance',
            'Sound System Coordination',
            'Energetic Personality',
            'Professional Attire',
            'Experience in Large Events',
        ],

        'Live Band / DJ': [
            'Full Band Setup',
            'DJ Equipment Included',
            'Customized Playlist',
            'Sound System Provided',
            'Lighting Effects',
            'Genre Variety',
            'Live Vocals',
            'Instrumental Performance',
            'MC Service Option',
            'Event Coordination',
            'Rehearsal Session',
            'Break Music Included',
            'Guest Song Requests',
            'Backup Equipment',
            'Stage Presence Training',
        ],

        'Event Styling / Decoration': [
            'Stage Design',
            'Backdrop Setup',
            'Floral Arrangements',
            'Table Centerpieces',
            'Thematic Styling',
            'Entrance Arch',
            'Photo Area Design',
            'LED Wall Integration',
            'Ceiling Drapes',
            'Lighting Coordination',
            'Seating Arrangement',
            'Props and Decor Rentals',
            'Color Theme Planning',
            'Venue Coordination',
            'Clean-up After Event',
        ],
    };

    // Return matching specs or fallback
    return (
        specsMap[category] || [
            'Customizable Service',
            'On-site Support',
            'Delivery and Setup',
            'Professional Staff',
            '24/7 Support Availability',
        ]
    );
}
